version: "3.9"

services:
  keycloak:
    build: .
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_DEBUG: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_LOG_LEVEL: info,org.keycloak.events:debug
    networks: [web]
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      smtp:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9000/health/ready || exit 1"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 3s
    volumes:
      # garde le thème en volume si tu veux itérer dessus, sinon commente-le et bake-le dans l'image
      - ./themes/bzhcamp/:/opt/keycloak/themes/bzhcamp/
    restart: unless-stopped

  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks: [web]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  smtp:
    image: axllent/mailpit:latest
    networks: [web]
    ports:
      - "1025:1025"
      - "8025:8025"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:8025/ || curl -fsS http://127.0.0.1:8025/ >/dev/null || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  nginx:
    image: nginx:1.25.3-alpine
    networks: [ web ]
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: "/Users/bichri/Documents/MasterClass Java/poc-openId/poc-keycloack-security/demo/myapp"
        target: /usr/share/nginx/html
        read_only: true
    restart: unless-stopped

networks:
  web:
    driver: bridge

volumes:
  pgdata:
